(
MAIN_MENU,
GET_TABLE_EROR,
GET_ERROR,
GET_ADDRESS,# спрашиваю адрес
GET_MONEY,#спрашиваю сколько потратил 
NO_IN_SP,
GET_CRED,
TOYS,
TOYS_MACHINE_INFO,
TANKS,
BANKNOTE,
RESTART,
OPROS_MENU,
GET_REK,
) = range(14)